[project]
name = "trabalho-pln-ii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dougbrdev", email = "douglasrodriguesdasilva53@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "gensim>=4.4.0",
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "spacy>=3.8.16",
]

[project.scripts]
trabalho-pln-ii = "trabalho_pln_ii:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
